// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.grab.grabfood.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The cancel code for a specific cancel reason.
 */
@JsonAdapter(CancelCode.Adapter.class)
public enum CancelCode {
  
  NUMBER_1001(1001),
  
  NUMBER_1002(1002),
  
  NUMBER_1003(1003),
  
  NUMBER_1004(1004),
  
  NUMBER_unknown_default_open_api(11184809);

  private Integer value;

  CancelCode(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CancelCode fromValue(Integer value) {
    for (CancelCode b : CancelCode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return NUMBER_unknown_default_open_api;
  }

  public static class Adapter extends TypeAdapter<CancelCode> {
    @Override
    public void write(final JsonWriter jsonWriter, final CancelCode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CancelCode read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return CancelCode.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    Integer value = jsonElement.getAsInt();
    CancelCode.fromValue(value);
  }
}

