// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.grab.grabfood.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.grab.grabfood.client.model.Currency;
import com.grab.grabfood.client.model.DineIn;
import com.grab.grabfood.client.model.GrabDiscount1;
import com.grab.grabfood.client.model.OrderCampaign;
import com.grab.grabfood.client.model.OrderFeatureFlags;
import com.grab.grabfood.client.model.OrderItem;
import com.grab.grabfood.client.model.OrderPrice;
import com.grab.grabfood.client.model.OrderPromo;
import com.grab.grabfood.client.model.OrderReadyEstimation;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.grab.grabfood.client.JSON;

/**
 * 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class EditOrderV2Response {
  public static final String SERIALIZED_NAME_ORDER_I_D = "orderID";
  @SerializedName(SERIALIZED_NAME_ORDER_I_D)
  private String orderID;

  public static final String SERIALIZED_NAME_SHORT_ORDER_NUMBER = "shortOrderNumber";
  @SerializedName(SERIALIZED_NAME_SHORT_ORDER_NUMBER)
  private String shortOrderNumber;

  public static final String SERIALIZED_NAME_MERCHANT_I_D = "merchantID";
  @SerializedName(SERIALIZED_NAME_MERCHANT_I_D)
  private String merchantID;

  public static final String SERIALIZED_NAME_PARTNER_MERCHANT_I_D = "partnerMerchantID";
  @SerializedName(SERIALIZED_NAME_PARTNER_MERCHANT_I_D)
  private String partnerMerchantID;

  /**
   * The payment method used. Refer to FAQs for more details about [paymentType](#section/Order/Does-the-paymentType-affect-partners).
   */
  @JsonAdapter(PaymentTypeEnum.Adapter.class)
  public enum PaymentTypeEnum {
    CASH("CASH"),
    
    CASHLESS("CASHLESS"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    PaymentTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PaymentTypeEnum fromValue(String value) {
      for (PaymentTypeEnum b : PaymentTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }

    public static class Adapter extends TypeAdapter<PaymentTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PaymentTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PaymentTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PaymentTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      PaymentTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PAYMENT_TYPE = "paymentType";
  @SerializedName(SERIALIZED_NAME_PAYMENT_TYPE)
  private PaymentTypeEnum paymentType;

  public static final String SERIALIZED_NAME_CUTLERY = "cutlery";
  @SerializedName(SERIALIZED_NAME_CUTLERY)
  private Boolean cutlery;

  public static final String SERIALIZED_NAME_ORDER_TIME = "orderTime";
  @SerializedName(SERIALIZED_NAME_ORDER_TIME)
  private String orderTime;

  public static final String SERIALIZED_NAME_SUBMIT_TIME = "submitTime";
  @SerializedName(SERIALIZED_NAME_SUBMIT_TIME)
  private OffsetDateTime submitTime;

  public static final String SERIALIZED_NAME_COMPLETE_TIME = "completeTime";
  @SerializedName(SERIALIZED_NAME_COMPLETE_TIME)
  private OffsetDateTime completeTime;

  public static final String SERIALIZED_NAME_SCHEDULED_TIME = "scheduledTime";
  @SerializedName(SERIALIZED_NAME_SCHEDULED_TIME)
  private String scheduledTime;

  public static final String SERIALIZED_NAME_ORDER_STATE = "orderState";
  @SerializedName(SERIALIZED_NAME_ORDER_STATE)
  private String orderState;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private Currency currency;

  public static final String SERIALIZED_NAME_FEATURE_FLAGS = "featureFlags";
  @SerializedName(SERIALIZED_NAME_FEATURE_FLAGS)
  private OrderFeatureFlags featureFlags;

  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  private List<OrderItem> items = new ArrayList<>();

  public static final String SERIALIZED_NAME_CAMPAIGNS = "campaigns";
  @SerializedName(SERIALIZED_NAME_CAMPAIGNS)
  private List<OrderCampaign> campaigns;

  public static final String SERIALIZED_NAME_PROMOS = "promos";
  @SerializedName(SERIALIZED_NAME_PROMOS)
  private List<OrderPromo> promos;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private OrderPrice price;

  public static final String SERIALIZED_NAME_DINE_IN = "dineIn";
  @SerializedName(SERIALIZED_NAME_DINE_IN)
  private DineIn dineIn;

  public static final String SERIALIZED_NAME_RECEIVER = "receiver";
  @SerializedName(SERIALIZED_NAME_RECEIVER)
  private Object receiver;

  public static final String SERIALIZED_NAME_ORDER_READY_ESTIMATION = "orderReadyEstimation";
  @SerializedName(SERIALIZED_NAME_ORDER_READY_ESTIMATION)
  private OrderReadyEstimation orderReadyEstimation;

  public static final String SERIALIZED_NAME_MEMBERSHIP_I_D = "membershipID";
  @SerializedName(SERIALIZED_NAME_MEMBERSHIP_I_D)
  private String membershipID;

  public static final String SERIALIZED_NAME_DISCOUNTS = "discounts";
  @SerializedName(SERIALIZED_NAME_DISCOUNTS)
  private List<GrabDiscount1> discounts;

  public static final String SERIALIZED_NAME_PAYMENTS = "payments";
  @SerializedName(SERIALIZED_NAME_PAYMENTS)
  private List<String> payments = new ArrayList<>();

  public EditOrderV2Response() {
  }

  public EditOrderV2Response orderID(String orderID) {
    this.orderID = orderID;
    return this;
  }

  /**
   * The order&#39;s ID that is returned from GrabFood. Refer to FAQs for more details about [orderID and shortOrderNumber](#section/Order/What&#39;s-the-difference-between-orderID-and-shortOrderNumber).
   * @return orderID
   */
  @javax.annotation.Nullable
  public String getOrderID() {
    return orderID;
  }

  public void setOrderID(String orderID) {
    this.orderID = orderID;
  }


  public EditOrderV2Response shortOrderNumber(String shortOrderNumber) {
    this.shortOrderNumber = shortOrderNumber;
    return this;
  }

  /**
   * The GrabFood short order number. This is unique for each merchant per day. Refer to FAQs for more details about [orderID and shortOrderNumber](#section/Order/What&#39;s-the-difference-between-orderID-and-shortOrderNumber).
   * @return shortOrderNumber
   */
  @javax.annotation.Nullable
  public String getShortOrderNumber() {
    return shortOrderNumber;
  }

  public void setShortOrderNumber(String shortOrderNumber) {
    this.shortOrderNumber = shortOrderNumber;
  }


  public EditOrderV2Response merchantID(String merchantID) {
    this.merchantID = merchantID;
    return this;
  }

  /**
   * The merchant&#39;s ID that is in GrabFood&#39;s database.
   * @return merchantID
   */
  @javax.annotation.Nullable
  public String getMerchantID() {
    return merchantID;
  }

  public void setMerchantID(String merchantID) {
    this.merchantID = merchantID;
  }


  public EditOrderV2Response partnerMerchantID(String partnerMerchantID) {
    this.partnerMerchantID = partnerMerchantID;
    return this;
  }

  /**
   * The merchant&#39;s ID that is on the partner&#39;s database.
   * @return partnerMerchantID
   */
  @javax.annotation.Nullable
  public String getPartnerMerchantID() {
    return partnerMerchantID;
  }

  public void setPartnerMerchantID(String partnerMerchantID) {
    this.partnerMerchantID = partnerMerchantID;
  }


  public EditOrderV2Response paymentType(PaymentTypeEnum paymentType) {
    this.paymentType = paymentType;
    return this;
  }

  /**
   * The payment method used. Refer to FAQs for more details about [paymentType](#section/Order/Does-the-paymentType-affect-partners).
   * @return paymentType
   */
  @javax.annotation.Nullable
  public PaymentTypeEnum getPaymentType() {
    return paymentType;
  }

  public void setPaymentType(PaymentTypeEnum paymentType) {
    this.paymentType = paymentType;
  }


  public EditOrderV2Response cutlery(Boolean cutlery) {
    this.cutlery = cutlery;
    return this;
  }

  /**
   * The boolean value to indicate whether cutlery are needed or not. Refer to FAQs for more details about [cutlery](#section/Order/What-do-the-true-or-false-values-mean-for-cutlery).
   * @return cutlery
   */
  @javax.annotation.Nullable
  public Boolean getCutlery() {
    return cutlery;
  }

  public void setCutlery(Boolean cutlery) {
    this.cutlery = cutlery;
  }


  public EditOrderV2Response orderTime(String orderTime) {
    this.orderTime = orderTime;
    return this;
  }

  /**
   * The UTC time that a consumer places the order, based on ISO_8601/RFC3339.
   * @return orderTime
   */
  @javax.annotation.Nullable
  public String getOrderTime() {
    return orderTime;
  }

  public void setOrderTime(String orderTime) {
    this.orderTime = orderTime;
  }


  public EditOrderV2Response submitTime(OffsetDateTime submitTime) {
    this.submitTime = submitTime;
    return this;
  }

  /**
   * The order submit time, based on ISO_8601/RFC3339. &#x60;null&#x60; in EditOrder V2 response. Only present in the [List Orders](#tag/list-order) response.
   * @return submitTime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getSubmitTime() {
    return submitTime;
  }

  public void setSubmitTime(OffsetDateTime submitTime) {
    this.submitTime = submitTime;
  }


  public EditOrderV2Response completeTime(OffsetDateTime completeTime) {
    this.completeTime = completeTime;
    return this;
  }

  /**
   * The order complete time, based on ISO_8601/RFC3339. &#x60;null&#x60; in EditOrder V2 response. Only present in the [List Orders](#tag/list-order) response.
   * @return completeTime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCompleteTime() {
    return completeTime;
  }

  public void setCompleteTime(OffsetDateTime completeTime) {
    this.completeTime = completeTime;
  }


  public EditOrderV2Response scheduledTime(String scheduledTime) {
    this.scheduledTime = scheduledTime;
    return this;
  }

  /**
   * The order scheduled time, based on ISO_8601/RFC3339. Empty for non-scheduled orders.
   * @return scheduledTime
   */
  @javax.annotation.Nullable
  public String getScheduledTime() {
    return scheduledTime;
  }

  public void setScheduledTime(String scheduledTime) {
    this.scheduledTime = scheduledTime;
  }


  public EditOrderV2Response orderState(String orderState) {
    this.orderState = orderState;
    return this;
  }

  /**
   * The state of the order. Empty in EditOrder V2 response. Only present in the [List Orders](#tag/list-order) response. Refer to [Order States](#section/Order-states).
   * @return orderState
   */
  @javax.annotation.Nullable
  public String getOrderState() {
    return orderState;
  }

  public void setOrderState(String orderState) {
    this.orderState = orderState;
  }


  public EditOrderV2Response currency(Currency currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nullable
  public Currency getCurrency() {
    return currency;
  }

  public void setCurrency(Currency currency) {
    this.currency = currency;
  }


  public EditOrderV2Response featureFlags(OrderFeatureFlags featureFlags) {
    this.featureFlags = featureFlags;
    return this;
  }

  /**
   * Get featureFlags
   * @return featureFlags
   */
  @javax.annotation.Nullable
  public OrderFeatureFlags getFeatureFlags() {
    return featureFlags;
  }

  public void setFeatureFlags(OrderFeatureFlags featureFlags) {
    this.featureFlags = featureFlags;
  }


  public EditOrderV2Response items(List<OrderItem> items) {
    this.items = items;
    return this;
  }

  public EditOrderV2Response addItemsItem(OrderItem itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * The ordered items in an array of JSON Object. 
   * @return items
   */
  @javax.annotation.Nullable
  public List<OrderItem> getItems() {
    return items;
  }

  public void setItems(List<OrderItem> items) {
    this.items = items;
  }


  public EditOrderV2Response campaigns(List<OrderCampaign> campaigns) {
    this.campaigns = campaigns;
    return this;
  }

  public EditOrderV2Response addCampaignsItem(OrderCampaign campaignsItem) {
    if (this.campaigns == null) {
      this.campaigns = new ArrayList<>();
    }
    this.campaigns.add(campaignsItem);
    return this;
  }

  /**
   * The campaigns that are applicable for the order. &#x60;null&#x60; when there is no campaign applied. Only campaigns that are funded by merchants will be sent. 
   * @return campaigns
   */
  @javax.annotation.Nullable
  public List<OrderCampaign> getCampaigns() {
    return campaigns;
  }

  public void setCampaigns(List<OrderCampaign> campaigns) {
    this.campaigns = campaigns;
  }


  public EditOrderV2Response promos(List<OrderPromo> promos) {
    this.promos = promos;
    return this;
  }

  public EditOrderV2Response addPromosItem(OrderPromo promosItem) {
    if (this.promos == null) {
      this.promos = new ArrayList<>();
    }
    this.promos.add(promosItem);
    return this;
  }

  /**
   * An array of promotion objects. &#x60;null&#x60; when there is no promo code applied. Only promotions that are funded by merchants will be sent.
   * @return promos
   */
  @javax.annotation.Nullable
  public List<OrderPromo> getPromos() {
    return promos;
  }

  public void setPromos(List<OrderPromo> promos) {
    this.promos = promos;
  }


  public EditOrderV2Response price(OrderPrice price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   */
  @javax.annotation.Nullable
  public OrderPrice getPrice() {
    return price;
  }

  public void setPrice(OrderPrice price) {
    this.price = price;
  }


  public EditOrderV2Response dineIn(DineIn dineIn) {
    this.dineIn = dineIn;
    return this;
  }

  /**
   * Get dineIn
   * @return dineIn
   */
  @javax.annotation.Nullable
  public DineIn getDineIn() {
    return dineIn;
  }

  public void setDineIn(DineIn dineIn) {
    this.dineIn = dineIn;
  }


  public EditOrderV2Response receiver(Object receiver) {
    this.receiver = receiver;
    return this;
  }

  /**
   * This field is set to &#x60;null&#x60; in the EditOrder V2 response. Refer to the [Submit Order](#tag/submit-order-webhook/operation/submit-order-webhook) payload for the complete receiver information.
   * @return receiver
   */
  @javax.annotation.Nullable
  public Object getReceiver() {
    return receiver;
  }

  public void setReceiver(Object receiver) {
    this.receiver = receiver;
  }


  public EditOrderV2Response orderReadyEstimation(OrderReadyEstimation orderReadyEstimation) {
    this.orderReadyEstimation = orderReadyEstimation;
    return this;
  }

  /**
   * Get orderReadyEstimation
   * @return orderReadyEstimation
   */
  @javax.annotation.Nullable
  public OrderReadyEstimation getOrderReadyEstimation() {
    return orderReadyEstimation;
  }

  public void setOrderReadyEstimation(OrderReadyEstimation orderReadyEstimation) {
    this.orderReadyEstimation = orderReadyEstimation;
  }


  public EditOrderV2Response membershipID(String membershipID) {
    this.membershipID = membershipID;
    return this;
  }

  /**
   * Membership ID for loyalty project. Only present for loyalty program partners. Empty if not applicable.
   * @return membershipID
   */
  @javax.annotation.Nullable
  public String getMembershipID() {
    return membershipID;
  }

  public void setMembershipID(String membershipID) {
    this.membershipID = membershipID;
  }


  public EditOrderV2Response discounts(List<GrabDiscount1> discounts) {
    this.discounts = discounts;
    return this;
  }

  public EditOrderV2Response addDiscountsItem(GrabDiscount1 discountsItem) {
    if (this.discounts == null) {
      this.discounts = new ArrayList<>();
    }
    this.discounts.add(discountsItem);
    return this;
  }

  /**
   * The discounts that are applicable for the paybill order in dineout STO case. &#x60;null&#x60; when there is no discount applied. This is only applicable for STO order 
   * @return discounts
   */
  @javax.annotation.Nullable
  public List<GrabDiscount1> getDiscounts() {
    return discounts;
  }

  public void setDiscounts(List<GrabDiscount1> discounts) {
    this.discounts = discounts;
  }


  public EditOrderV2Response payments(List<String> payments) {
    this.payments = payments;
    return this;
  }

  public EditOrderV2Response addPaymentsItem(String paymentsItem) {
    if (this.payments == null) {
      this.payments = new ArrayList<>();
    }
    this.payments.add(paymentsItem);
    return this;
  }

  /**
   * This field is set to &#x60;null&#x60; in the EditOrder V2 response. Refer to the [Submit Order](#tag/submit-order-webhook/operation/submit-order-webhook) payload for the complete payment details.
   * @return payments
   */
  @javax.annotation.Nullable
  public List<String> getPayments() {
    return payments;
  }

  public void setPayments(List<String> payments) {
    this.payments = payments;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the EditOrderV2Response instance itself
   */
  public EditOrderV2Response putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditOrderV2Response editOrderV2Response = (EditOrderV2Response) o;
    return Objects.equals(this.orderID, editOrderV2Response.orderID) &&
        Objects.equals(this.shortOrderNumber, editOrderV2Response.shortOrderNumber) &&
        Objects.equals(this.merchantID, editOrderV2Response.merchantID) &&
        Objects.equals(this.partnerMerchantID, editOrderV2Response.partnerMerchantID) &&
        Objects.equals(this.paymentType, editOrderV2Response.paymentType) &&
        Objects.equals(this.cutlery, editOrderV2Response.cutlery) &&
        Objects.equals(this.orderTime, editOrderV2Response.orderTime) &&
        Objects.equals(this.submitTime, editOrderV2Response.submitTime) &&
        Objects.equals(this.completeTime, editOrderV2Response.completeTime) &&
        Objects.equals(this.scheduledTime, editOrderV2Response.scheduledTime) &&
        Objects.equals(this.orderState, editOrderV2Response.orderState) &&
        Objects.equals(this.currency, editOrderV2Response.currency) &&
        Objects.equals(this.featureFlags, editOrderV2Response.featureFlags) &&
        Objects.equals(this.items, editOrderV2Response.items) &&
        Objects.equals(this.campaigns, editOrderV2Response.campaigns) &&
        Objects.equals(this.promos, editOrderV2Response.promos) &&
        Objects.equals(this.price, editOrderV2Response.price) &&
        Objects.equals(this.dineIn, editOrderV2Response.dineIn) &&
        Objects.equals(this.receiver, editOrderV2Response.receiver) &&
        Objects.equals(this.orderReadyEstimation, editOrderV2Response.orderReadyEstimation) &&
        Objects.equals(this.membershipID, editOrderV2Response.membershipID) &&
        Objects.equals(this.discounts, editOrderV2Response.discounts) &&
        Objects.equals(this.payments, editOrderV2Response.payments)&&
        Objects.equals(this.additionalProperties, editOrderV2Response.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderID, shortOrderNumber, merchantID, partnerMerchantID, paymentType, cutlery, orderTime, submitTime, completeTime, scheduledTime, orderState, currency, featureFlags, items, campaigns, promos, price, dineIn, receiver, orderReadyEstimation, membershipID, discounts, payments, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditOrderV2Response {\n");
    sb.append("    orderID: ").append(toIndentedString(orderID)).append("\n");
    sb.append("    shortOrderNumber: ").append(toIndentedString(shortOrderNumber)).append("\n");
    sb.append("    merchantID: ").append(toIndentedString(merchantID)).append("\n");
    sb.append("    partnerMerchantID: ").append(toIndentedString(partnerMerchantID)).append("\n");
    sb.append("    paymentType: ").append(toIndentedString(paymentType)).append("\n");
    sb.append("    cutlery: ").append(toIndentedString(cutlery)).append("\n");
    sb.append("    orderTime: ").append(toIndentedString(orderTime)).append("\n");
    sb.append("    submitTime: ").append(toIndentedString(submitTime)).append("\n");
    sb.append("    completeTime: ").append(toIndentedString(completeTime)).append("\n");
    sb.append("    scheduledTime: ").append(toIndentedString(scheduledTime)).append("\n");
    sb.append("    orderState: ").append(toIndentedString(orderState)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    featureFlags: ").append(toIndentedString(featureFlags)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    campaigns: ").append(toIndentedString(campaigns)).append("\n");
    sb.append("    promos: ").append(toIndentedString(promos)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    dineIn: ").append(toIndentedString(dineIn)).append("\n");
    sb.append("    receiver: ").append(toIndentedString(receiver)).append("\n");
    sb.append("    orderReadyEstimation: ").append(toIndentedString(orderReadyEstimation)).append("\n");
    sb.append("    membershipID: ").append(toIndentedString(membershipID)).append("\n");
    sb.append("    discounts: ").append(toIndentedString(discounts)).append("\n");
    sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("orderID");
    openapiFields.add("shortOrderNumber");
    openapiFields.add("merchantID");
    openapiFields.add("partnerMerchantID");
    openapiFields.add("paymentType");
    openapiFields.add("cutlery");
    openapiFields.add("orderTime");
    openapiFields.add("submitTime");
    openapiFields.add("completeTime");
    openapiFields.add("scheduledTime");
    openapiFields.add("orderState");
    openapiFields.add("currency");
    openapiFields.add("featureFlags");
    openapiFields.add("items");
    openapiFields.add("campaigns");
    openapiFields.add("promos");
    openapiFields.add("price");
    openapiFields.add("dineIn");
    openapiFields.add("receiver");
    openapiFields.add("orderReadyEstimation");
    openapiFields.add("membershipID");
    openapiFields.add("discounts");
    openapiFields.add("payments");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EditOrderV2Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EditOrderV2Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EditOrderV2Response is not found in the empty JSON string", EditOrderV2Response.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("orderID") != null && !jsonObj.get("orderID").isJsonNull()) && !jsonObj.get("orderID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `orderID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("orderID").toString()));
      }
      if ((jsonObj.get("shortOrderNumber") != null && !jsonObj.get("shortOrderNumber").isJsonNull()) && !jsonObj.get("shortOrderNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shortOrderNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shortOrderNumber").toString()));
      }
      if ((jsonObj.get("merchantID") != null && !jsonObj.get("merchantID").isJsonNull()) && !jsonObj.get("merchantID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `merchantID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merchantID").toString()));
      }
      if ((jsonObj.get("partnerMerchantID") != null && !jsonObj.get("partnerMerchantID").isJsonNull()) && !jsonObj.get("partnerMerchantID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `partnerMerchantID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("partnerMerchantID").toString()));
      }
      if ((jsonObj.get("paymentType") != null && !jsonObj.get("paymentType").isJsonNull()) && !jsonObj.get("paymentType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paymentType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymentType").toString()));
      }
      // validate the optional field `paymentType`
      if (jsonObj.get("paymentType") != null && !jsonObj.get("paymentType").isJsonNull()) {
        PaymentTypeEnum.validateJsonElement(jsonObj.get("paymentType"));
      }
      if ((jsonObj.get("orderTime") != null && !jsonObj.get("orderTime").isJsonNull()) && !jsonObj.get("orderTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `orderTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("orderTime").toString()));
      }
      if ((jsonObj.get("scheduledTime") != null && !jsonObj.get("scheduledTime").isJsonNull()) && !jsonObj.get("scheduledTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `scheduledTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("scheduledTime").toString()));
      }
      if ((jsonObj.get("orderState") != null && !jsonObj.get("orderState").isJsonNull()) && !jsonObj.get("orderState").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `orderState` to be a primitive type in the JSON string but got `%s`", jsonObj.get("orderState").toString()));
      }
      // validate the optional field `currency`
      if (jsonObj.get("currency") != null && !jsonObj.get("currency").isJsonNull()) {
        Currency.validateJsonElement(jsonObj.get("currency"));
      }
      // validate the optional field `featureFlags`
      if (jsonObj.get("featureFlags") != null && !jsonObj.get("featureFlags").isJsonNull()) {
        OrderFeatureFlags.validateJsonElement(jsonObj.get("featureFlags"));
      }
      if (jsonObj.get("items") != null && !jsonObj.get("items").isJsonNull()) {
        JsonArray jsonArrayitems = jsonObj.getAsJsonArray("items");
        if (jsonArrayitems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("items").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `items` to be an array in the JSON string but got `%s`", jsonObj.get("items").toString()));
          }

          // validate the optional field `items` (array)
          for (int i = 0; i < jsonArrayitems.size(); i++) {
            OrderItem.validateJsonElement(jsonArrayitems.get(i));
          };
        }
      }
      if (jsonObj.get("campaigns") != null && !jsonObj.get("campaigns").isJsonNull()) {
        JsonArray jsonArraycampaigns = jsonObj.getAsJsonArray("campaigns");
        if (jsonArraycampaigns != null) {
          // ensure the json data is an array
          if (!jsonObj.get("campaigns").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `campaigns` to be an array in the JSON string but got `%s`", jsonObj.get("campaigns").toString()));
          }

          // validate the optional field `campaigns` (array)
          for (int i = 0; i < jsonArraycampaigns.size(); i++) {
            OrderCampaign.validateJsonElement(jsonArraycampaigns.get(i));
          };
        }
      }
      if (jsonObj.get("promos") != null && !jsonObj.get("promos").isJsonNull()) {
        JsonArray jsonArraypromos = jsonObj.getAsJsonArray("promos");
        if (jsonArraypromos != null) {
          // ensure the json data is an array
          if (!jsonObj.get("promos").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `promos` to be an array in the JSON string but got `%s`", jsonObj.get("promos").toString()));
          }

          // validate the optional field `promos` (array)
          for (int i = 0; i < jsonArraypromos.size(); i++) {
            OrderPromo.validateJsonElement(jsonArraypromos.get(i));
          };
        }
      }
      // validate the optional field `price`
      if (jsonObj.get("price") != null && !jsonObj.get("price").isJsonNull()) {
        OrderPrice.validateJsonElement(jsonObj.get("price"));
      }
      // validate the optional field `dineIn`
      if (jsonObj.get("dineIn") != null && !jsonObj.get("dineIn").isJsonNull()) {
        DineIn.validateJsonElement(jsonObj.get("dineIn"));
      }
      // validate the optional field `orderReadyEstimation`
      if (jsonObj.get("orderReadyEstimation") != null && !jsonObj.get("orderReadyEstimation").isJsonNull()) {
        OrderReadyEstimation.validateJsonElement(jsonObj.get("orderReadyEstimation"));
      }
      if ((jsonObj.get("membershipID") != null && !jsonObj.get("membershipID").isJsonNull()) && !jsonObj.get("membershipID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `membershipID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("membershipID").toString()));
      }
      if (jsonObj.get("discounts") != null && !jsonObj.get("discounts").isJsonNull()) {
        JsonArray jsonArraydiscounts = jsonObj.getAsJsonArray("discounts");
        if (jsonArraydiscounts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("discounts").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `discounts` to be an array in the JSON string but got `%s`", jsonObj.get("discounts").toString()));
          }

          // validate the optional field `discounts` (array)
          for (int i = 0; i < jsonArraydiscounts.size(); i++) {
            GrabDiscount1.validateJsonElement(jsonArraydiscounts.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("payments") != null && !jsonObj.get("payments").isJsonNull() && !jsonObj.get("payments").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `payments` to be an array in the JSON string but got `%s`", jsonObj.get("payments").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EditOrderV2Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EditOrderV2Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EditOrderV2Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EditOrderV2Response.class));

       return (TypeAdapter<T>) new TypeAdapter<EditOrderV2Response>() {
           @Override
           public void write(JsonWriter out, EditOrderV2Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public EditOrderV2Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             EditOrderV2Response instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EditOrderV2Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EditOrderV2Response
   * @throws IOException if the JSON string is invalid with respect to EditOrderV2Response
   */
  public static EditOrderV2Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EditOrderV2Response.class);
  }

  /**
   * Convert an instance of EditOrderV2Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

