// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.grab.grabfood.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.grab.grabfood.client.model.Voucher;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.grab.grabfood.client.JSON;

/**
 * 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class GetDineInVoucherResponse {
  public static final String SERIALIZED_NAME_CERTIFICATE_I_D = "certificateID";
  @SerializedName(SERIALIZED_NAME_CERTIFICATE_I_D)
  private String certificateID;

  public static final String SERIALIZED_NAME_VOUCHER_CODE = "voucherCode";
  @SerializedName(SERIALIZED_NAME_VOUCHER_CODE)
  private String voucherCode;

  public static final String SERIALIZED_NAME_VOUCHER = "voucher";
  @SerializedName(SERIALIZED_NAME_VOUCHER)
  private Voucher voucher;

  /**
   * The status of the dine-in voucher purchased. Only active voucher is eligible for redemption.
   */
  @JsonAdapter(VoucherStatusEnum.Adapter.class)
  public enum VoucherStatusEnum {
    ACTIVE("ACTIVE"),
    
    REDEEMED("REDEEMED"),
    
    EXPIRED("EXPIRED"),
    
    REFUNDED("REFUNDED"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    VoucherStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static VoucherStatusEnum fromValue(String value) {
      for (VoucherStatusEnum b : VoucherStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }

    public static class Adapter extends TypeAdapter<VoucherStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final VoucherStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public VoucherStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return VoucherStatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      VoucherStatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_VOUCHER_STATUS = "voucherStatus";
  @SerializedName(SERIALIZED_NAME_VOUCHER_STATUS)
  private VoucherStatusEnum voucherStatus;

  public static final String SERIALIZED_NAME_MERCHANT_I_D = "merchantID";
  @SerializedName(SERIALIZED_NAME_MERCHANT_I_D)
  private String merchantID;

  public static final String SERIALIZED_NAME_CAMPAIGN_I_D = "campaignID";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_I_D)
  private String campaignID;

  public GetDineInVoucherResponse() {
  }

  public GetDineInVoucherResponse certificateID(String certificateID) {
    this.certificateID = certificateID;
    return this;
  }

  /**
   * This certificateID is decoded from scanning the QR code, and 1:1 mapping with &#x60;voucherCode&#x60;.
   * @return certificateID
   */
  @javax.annotation.Nullable
  public String getCertificateID() {
    return certificateID;
  }

  public void setCertificateID(String certificateID) {
    this.certificateID = certificateID;
  }


  public GetDineInVoucherResponse voucherCode(String voucherCode) {
    this.voucherCode = voucherCode;
    return this;
  }

  /**
   * A short code for the dine-in voucher purchased by the user.
   * @return voucherCode
   */
  @javax.annotation.Nullable
  public String getVoucherCode() {
    return voucherCode;
  }

  public void setVoucherCode(String voucherCode) {
    this.voucherCode = voucherCode;
  }


  public GetDineInVoucherResponse voucher(Voucher voucher) {
    this.voucher = voucher;
    return this;
  }

  /**
   * Get voucher
   * @return voucher
   */
  @javax.annotation.Nullable
  public Voucher getVoucher() {
    return voucher;
  }

  public void setVoucher(Voucher voucher) {
    this.voucher = voucher;
  }


  public GetDineInVoucherResponse voucherStatus(VoucherStatusEnum voucherStatus) {
    this.voucherStatus = voucherStatus;
    return this;
  }

  /**
   * The status of the dine-in voucher purchased. Only active voucher is eligible for redemption.
   * @return voucherStatus
   */
  @javax.annotation.Nullable
  public VoucherStatusEnum getVoucherStatus() {
    return voucherStatus;
  }

  public void setVoucherStatus(VoucherStatusEnum voucherStatus) {
    this.voucherStatus = voucherStatus;
  }


  public GetDineInVoucherResponse merchantID(String merchantID) {
    this.merchantID = merchantID;
    return this;
  }

  /**
   * The merchant&#39;s ID that is in GrabFood&#39;s database.
   * @return merchantID
   */
  @javax.annotation.Nullable
  public String getMerchantID() {
    return merchantID;
  }

  public void setMerchantID(String merchantID) {
    this.merchantID = merchantID;
  }


  public GetDineInVoucherResponse campaignID(String campaignID) {
    this.campaignID = campaignID;
    return this;
  }

  /**
   * The dine-in voucher campaign&#39;s ID in GrabFood&#39;s database.
   * @return campaignID
   */
  @javax.annotation.Nullable
  public String getCampaignID() {
    return campaignID;
  }

  public void setCampaignID(String campaignID) {
    this.campaignID = campaignID;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GetDineInVoucherResponse instance itself
   */
  public GetDineInVoucherResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDineInVoucherResponse getDineInVoucherResponse = (GetDineInVoucherResponse) o;
    return Objects.equals(this.certificateID, getDineInVoucherResponse.certificateID) &&
        Objects.equals(this.voucherCode, getDineInVoucherResponse.voucherCode) &&
        Objects.equals(this.voucher, getDineInVoucherResponse.voucher) &&
        Objects.equals(this.voucherStatus, getDineInVoucherResponse.voucherStatus) &&
        Objects.equals(this.merchantID, getDineInVoucherResponse.merchantID) &&
        Objects.equals(this.campaignID, getDineInVoucherResponse.campaignID)&&
        Objects.equals(this.additionalProperties, getDineInVoucherResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificateID, voucherCode, voucher, voucherStatus, merchantID, campaignID, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDineInVoucherResponse {\n");
    sb.append("    certificateID: ").append(toIndentedString(certificateID)).append("\n");
    sb.append("    voucherCode: ").append(toIndentedString(voucherCode)).append("\n");
    sb.append("    voucher: ").append(toIndentedString(voucher)).append("\n");
    sb.append("    voucherStatus: ").append(toIndentedString(voucherStatus)).append("\n");
    sb.append("    merchantID: ").append(toIndentedString(merchantID)).append("\n");
    sb.append("    campaignID: ").append(toIndentedString(campaignID)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("certificateID");
    openapiFields.add("voucherCode");
    openapiFields.add("voucher");
    openapiFields.add("voucherStatus");
    openapiFields.add("merchantID");
    openapiFields.add("campaignID");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetDineInVoucherResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetDineInVoucherResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetDineInVoucherResponse is not found in the empty JSON string", GetDineInVoucherResponse.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("certificateID") != null && !jsonObj.get("certificateID").isJsonNull()) && !jsonObj.get("certificateID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `certificateID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("certificateID").toString()));
      }
      if ((jsonObj.get("voucherCode") != null && !jsonObj.get("voucherCode").isJsonNull()) && !jsonObj.get("voucherCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `voucherCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("voucherCode").toString()));
      }
      // validate the optional field `voucher`
      if (jsonObj.get("voucher") != null && !jsonObj.get("voucher").isJsonNull()) {
        Voucher.validateJsonElement(jsonObj.get("voucher"));
      }
      if ((jsonObj.get("voucherStatus") != null && !jsonObj.get("voucherStatus").isJsonNull()) && !jsonObj.get("voucherStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `voucherStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("voucherStatus").toString()));
      }
      // validate the optional field `voucherStatus`
      if (jsonObj.get("voucherStatus") != null && !jsonObj.get("voucherStatus").isJsonNull()) {
        VoucherStatusEnum.validateJsonElement(jsonObj.get("voucherStatus"));
      }
      if ((jsonObj.get("merchantID") != null && !jsonObj.get("merchantID").isJsonNull()) && !jsonObj.get("merchantID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `merchantID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merchantID").toString()));
      }
      if ((jsonObj.get("campaignID") != null && !jsonObj.get("campaignID").isJsonNull()) && !jsonObj.get("campaignID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `campaignID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("campaignID").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetDineInVoucherResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetDineInVoucherResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetDineInVoucherResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetDineInVoucherResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetDineInVoucherResponse>() {
           @Override
           public void write(JsonWriter out, GetDineInVoucherResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GetDineInVoucherResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             GetDineInVoucherResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetDineInVoucherResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetDineInVoucherResponse
   * @throws IOException if the JSON string is invalid with respect to GetDineInVoucherResponse
   */
  public static GetDineInVoucherResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetDineInVoucherResponse.class);
  }

  /**
   * Convert an instance of GetDineInVoucherResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

