// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.grab.grabfood.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.grab.grabfood.client.JSON;

/**
 * Obtain contains user&#39;s point details.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class GetMembershipNativeResponsePointInfo {
  public static final String SERIALIZED_NAME_CURRENT_POINTS = "currentPoints";
  @SerializedName(SERIALIZED_NAME_CURRENT_POINTS)
  private Long currentPoints;

  public static final String SERIALIZED_NAME_MAX_POINTS = "maxPoints";
  @SerializedName(SERIALIZED_NAME_MAX_POINTS)
  private Long maxPoints;

  public static final String SERIALIZED_NAME_EXPIRE_POINTS = "expirePoints";
  @SerializedName(SERIALIZED_NAME_EXPIRE_POINTS)
  private Long expirePoints;

  public GetMembershipNativeResponsePointInfo() {
  }

  public GetMembershipNativeResponsePointInfo currentPoints(Long currentPoints) {
    this.currentPoints = currentPoints;
    return this;
  }

  /**
   * Point that user currently obtained.
   * @return currentPoints
   */
  @javax.annotation.Nullable
  public Long getCurrentPoints() {
    return currentPoints;
  }

  public void setCurrentPoints(Long currentPoints) {
    this.currentPoints = currentPoints;
  }


  public GetMembershipNativeResponsePointInfo maxPoints(Long maxPoints) {
    this.maxPoints = maxPoints;
    return this;
  }

  /**
   * Maximum point that user can obtain.
   * @return maxPoints
   */
  @javax.annotation.Nullable
  public Long getMaxPoints() {
    return maxPoints;
  }

  public void setMaxPoints(Long maxPoints) {
    this.maxPoints = maxPoints;
  }


  public GetMembershipNativeResponsePointInfo expirePoints(Long expirePoints) {
    this.expirePoints = expirePoints;
    return this;
  }

  /**
   * Points that would get expired in future.
   * @return expirePoints
   */
  @javax.annotation.Nullable
  public Long getExpirePoints() {
    return expirePoints;
  }

  public void setExpirePoints(Long expirePoints) {
    this.expirePoints = expirePoints;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GetMembershipNativeResponsePointInfo instance itself
   */
  public GetMembershipNativeResponsePointInfo putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMembershipNativeResponsePointInfo getMembershipNativeResponsePointInfo = (GetMembershipNativeResponsePointInfo) o;
    return Objects.equals(this.currentPoints, getMembershipNativeResponsePointInfo.currentPoints) &&
        Objects.equals(this.maxPoints, getMembershipNativeResponsePointInfo.maxPoints) &&
        Objects.equals(this.expirePoints, getMembershipNativeResponsePointInfo.expirePoints)&&
        Objects.equals(this.additionalProperties, getMembershipNativeResponsePointInfo.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentPoints, maxPoints, expirePoints, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMembershipNativeResponsePointInfo {\n");
    sb.append("    currentPoints: ").append(toIndentedString(currentPoints)).append("\n");
    sb.append("    maxPoints: ").append(toIndentedString(maxPoints)).append("\n");
    sb.append("    expirePoints: ").append(toIndentedString(expirePoints)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("currentPoints");
    openapiFields.add("maxPoints");
    openapiFields.add("expirePoints");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetMembershipNativeResponsePointInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetMembershipNativeResponsePointInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetMembershipNativeResponsePointInfo is not found in the empty JSON string", GetMembershipNativeResponsePointInfo.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetMembershipNativeResponsePointInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetMembershipNativeResponsePointInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetMembershipNativeResponsePointInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetMembershipNativeResponsePointInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<GetMembershipNativeResponsePointInfo>() {
           @Override
           public void write(JsonWriter out, GetMembershipNativeResponsePointInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GetMembershipNativeResponsePointInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             GetMembershipNativeResponsePointInfo instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetMembershipNativeResponsePointInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetMembershipNativeResponsePointInfo
   * @throws IOException if the JSON string is invalid with respect to GetMembershipNativeResponsePointInfo
   */
  public static GetMembershipNativeResponsePointInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetMembershipNativeResponsePointInfo.class);
  }

  /**
   * Convert an instance of GetMembershipNativeResponsePointInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

