// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.grab.grabfood.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.grab.grabfood.client.JSON;

/**
 * A JSON object reflects the real money the merchant receives. Only applicable for Dine out STO case. &#x60;null&#x60; if not applicable. Only present in submitOrder webhook. Not present in [ListOrder](#tag/list-order/operation/list-orders) response.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class MerchantEarning {
  public static final String SERIALIZED_NAME_REVENUE = "revenue";
  @SerializedName(SERIALIZED_NAME_REVENUE)
  private Long revenue;

  public static final String SERIALIZED_NAME_NET_EARNING = "netEarning";
  @SerializedName(SERIALIZED_NAME_NET_EARNING)
  private Long netEarning;

  public static final String SERIALIZED_NAME_MEX_FUND_DISCOUNT = "mexFundDiscount";
  @SerializedName(SERIALIZED_NAME_MEX_FUND_DISCOUNT)
  private Long mexFundDiscount;

  public static final String SERIALIZED_NAME_COMMISSION = "commission";
  @SerializedName(SERIALIZED_NAME_COMMISSION)
  private Long commission;

  public MerchantEarning() {
  }

  public MerchantEarning revenue(Long revenue) {
    this.revenue = revenue;
    return this;
  }

  /**
   * The revenue of merchant should receive. revenue &#x3D; price.eaterpayment - mexfunddiscount
   * @return revenue
   */
  @javax.annotation.Nullable
  public Long getRevenue() {
    return revenue;
  }

  public void setRevenue(Long revenue) {
    this.revenue = revenue;
  }


  public MerchantEarning netEarning(Long netEarning) {
    this.netEarning = netEarning;
    return this;
  }

  /**
   * The netEarning of merchant should receive. netEarning &#x3D; revenue - commission
   * @return netEarning
   */
  @javax.annotation.Nullable
  public Long getNetEarning() {
    return netEarning;
  }

  public void setNetEarning(Long netEarning) {
    this.netEarning = netEarning;
  }


  public MerchantEarning mexFundDiscount(Long mexFundDiscount) {
    this.mexFundDiscount = mexFundDiscount;
    return this;
  }

  /**
   * The mexFundDiscount that user applied from grab app in this payment
   * @return mexFundDiscount
   */
  @javax.annotation.Nullable
  public Long getMexFundDiscount() {
    return mexFundDiscount;
  }

  public void setMexFundDiscount(Long mexFundDiscount) {
    this.mexFundDiscount = mexFundDiscount;
  }


  public MerchantEarning commission(Long commission) {
    this.commission = commission;
    return this;
  }

  /**
   * The commission that grab need charge from this pay merchant transaction.
   * @return commission
   */
  @javax.annotation.Nullable
  public Long getCommission() {
    return commission;
  }

  public void setCommission(Long commission) {
    this.commission = commission;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the MerchantEarning instance itself
   */
  public MerchantEarning putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantEarning merchantEarning = (MerchantEarning) o;
    return Objects.equals(this.revenue, merchantEarning.revenue) &&
        Objects.equals(this.netEarning, merchantEarning.netEarning) &&
        Objects.equals(this.mexFundDiscount, merchantEarning.mexFundDiscount) &&
        Objects.equals(this.commission, merchantEarning.commission)&&
        Objects.equals(this.additionalProperties, merchantEarning.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(revenue, netEarning, mexFundDiscount, commission, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantEarning {\n");
    sb.append("    revenue: ").append(toIndentedString(revenue)).append("\n");
    sb.append("    netEarning: ").append(toIndentedString(netEarning)).append("\n");
    sb.append("    mexFundDiscount: ").append(toIndentedString(mexFundDiscount)).append("\n");
    sb.append("    commission: ").append(toIndentedString(commission)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("revenue");
    openapiFields.add("netEarning");
    openapiFields.add("mexFundDiscount");
    openapiFields.add("commission");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MerchantEarning
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MerchantEarning.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MerchantEarning is not found in the empty JSON string", MerchantEarning.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MerchantEarning.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MerchantEarning' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MerchantEarning> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MerchantEarning.class));

       return (TypeAdapter<T>) new TypeAdapter<MerchantEarning>() {
           @Override
           public void write(JsonWriter out, MerchantEarning value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public MerchantEarning read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             MerchantEarning instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MerchantEarning given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MerchantEarning
   * @throws IOException if the JSON string is invalid with respect to MerchantEarning
   */
  public static MerchantEarning fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MerchantEarning.class);
  }

  /**
   * Convert an instance of MerchantEarning to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

