// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.grab.grabfood.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.grab.grabfood.client.JSON;

/**
 * Object contains store status info
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class StoreStatusResponse {
  /**
   * The code of store close reason. Blank indicates store is currently open.
   */
  @JsonAdapter(CloseReasonEnum.Adapter.class)
  public enum CloseReasonEnum {
    MEX_PAUSED("mex_paused"),
    
    OPS_PAUSED("ops_paused"),
    
    OUT_OF_SPECIAL_OPENING_HOURS("out_of_special_opening_hours"),
    
    OUT_OF_OPENING_HOURS("out_of_opening_hours"),
    
    INACTIVE("inactive"),
    
    OPS_PAUSED_WITHOUT_COMM("ops_paused_without_comm"),
    
    RESTRICTED("restricted"),
    
    SUSPENDED("suspended"),
    
    PARSE_DATA_FAIL("parse_data_fail"),
    
    EMPTY(""),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    CloseReasonEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CloseReasonEnum fromValue(String value) {
      for (CloseReasonEnum b : CloseReasonEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }

    public static class Adapter extends TypeAdapter<CloseReasonEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CloseReasonEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CloseReasonEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CloseReasonEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CloseReasonEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CLOSE_REASON = "closeReason";
  @SerializedName(SERIALIZED_NAME_CLOSE_REASON)
  private CloseReasonEnum closeReason;

  public static final String SERIALIZED_NAME_IS_IN_SPECIAL_OPENING_HOUR_RANGE = "isInSpecialOpeningHourRange";
  @SerializedName(SERIALIZED_NAME_IS_IN_SPECIAL_OPENING_HOUR_RANGE)
  private Boolean isInSpecialOpeningHourRange;

  public static final String SERIALIZED_NAME_IS_OPEN = "isOpen";
  @SerializedName(SERIALIZED_NAME_IS_OPEN)
  private Boolean isOpen;

  public StoreStatusResponse() {
  }

  public StoreStatusResponse closeReason(CloseReasonEnum closeReason) {
    this.closeReason = closeReason;
    return this;
  }

  /**
   * The code of store close reason. Blank indicates store is currently open.
   * @return closeReason
   */
  @javax.annotation.Nonnull
  public CloseReasonEnum getCloseReason() {
    return closeReason;
  }

  public void setCloseReason(CloseReasonEnum closeReason) {
    this.closeReason = closeReason;
  }


  public StoreStatusResponse isInSpecialOpeningHourRange(Boolean isInSpecialOpeningHourRange) {
    this.isInSpecialOpeningHourRange = isInSpecialOpeningHourRange;
    return this;
  }

  /**
   * Indicate whether the store is in special opening hour range.
   * @return isInSpecialOpeningHourRange
   */
  @javax.annotation.Nonnull
  public Boolean getIsInSpecialOpeningHourRange() {
    return isInSpecialOpeningHourRange;
  }

  public void setIsInSpecialOpeningHourRange(Boolean isInSpecialOpeningHourRange) {
    this.isInSpecialOpeningHourRange = isInSpecialOpeningHourRange;
  }


  public StoreStatusResponse isOpen(Boolean isOpen) {
    this.isOpen = isOpen;
    return this;
  }

  /**
   * Indicate whether the store is open.
   * @return isOpen
   */
  @javax.annotation.Nonnull
  public Boolean getIsOpen() {
    return isOpen;
  }

  public void setIsOpen(Boolean isOpen) {
    this.isOpen = isOpen;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the StoreStatusResponse instance itself
   */
  public StoreStatusResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoreStatusResponse storeStatusResponse = (StoreStatusResponse) o;
    return Objects.equals(this.closeReason, storeStatusResponse.closeReason) &&
        Objects.equals(this.isInSpecialOpeningHourRange, storeStatusResponse.isInSpecialOpeningHourRange) &&
        Objects.equals(this.isOpen, storeStatusResponse.isOpen)&&
        Objects.equals(this.additionalProperties, storeStatusResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(closeReason, isInSpecialOpeningHourRange, isOpen, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoreStatusResponse {\n");
    sb.append("    closeReason: ").append(toIndentedString(closeReason)).append("\n");
    sb.append("    isInSpecialOpeningHourRange: ").append(toIndentedString(isInSpecialOpeningHourRange)).append("\n");
    sb.append("    isOpen: ").append(toIndentedString(isOpen)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("closeReason");
    openapiFields.add("isInSpecialOpeningHourRange");
    openapiFields.add("isOpen");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("closeReason");
    openapiRequiredFields.add("isInSpecialOpeningHourRange");
    openapiRequiredFields.add("isOpen");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StoreStatusResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StoreStatusResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in StoreStatusResponse is not found in the empty JSON string", StoreStatusResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : StoreStatusResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("closeReason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `closeReason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("closeReason").toString()));
      }
      // validate the required field `closeReason`
      CloseReasonEnum.validateJsonElement(jsonObj.get("closeReason"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StoreStatusResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StoreStatusResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StoreStatusResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StoreStatusResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<StoreStatusResponse>() {
           @Override
           public void write(JsonWriter out, StoreStatusResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public StoreStatusResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             StoreStatusResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StoreStatusResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StoreStatusResponse
   * @throws IOException if the JSON string is invalid with respect to StoreStatusResponse
   */
  public static StoreStatusResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StoreStatusResponse.class);
  }

  /**
   * Convert an instance of StoreStatusResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

