// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.grab.grabfood.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.grab.grabfood.client.JSON;

/**
 * Object contain update store special hour response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class UpdateSpecialHourResponse {
  /**
   * Gets or Sets errorReasons
   */
  @JsonAdapter(ErrorReasonsEnum.Adapter.class)
  public enum ErrorReasonsEnum {
    PENDING_ORDERS("PendingOrders"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    ErrorReasonsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ErrorReasonsEnum fromValue(String value) {
      for (ErrorReasonsEnum b : ErrorReasonsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }

    public static class Adapter extends TypeAdapter<ErrorReasonsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ErrorReasonsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ErrorReasonsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ErrorReasonsEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ErrorReasonsEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ERROR_REASONS = "errorReasons";
  @SerializedName(SERIALIZED_NAME_ERROR_REASONS)
  private List<ErrorReasonsEnum> errorReasons;

  public static final String SERIALIZED_NAME_ORDER_COUNT = "orderCount";
  @SerializedName(SERIALIZED_NAME_ORDER_COUNT)
  private Long orderCount;

  public static final String SERIALIZED_NAME_SCHEDULED_ORDER_COUNT = "scheduledOrderCount";
  @SerializedName(SERIALIZED_NAME_SCHEDULED_ORDER_COUNT)
  private Long scheduledOrderCount;

  public static final String SERIALIZED_NAME_CLOSE_IMMEDIATELY = "closeImmediately";
  @SerializedName(SERIALIZED_NAME_CLOSE_IMMEDIATELY)
  private Boolean closeImmediately;

  public UpdateSpecialHourResponse() {
  }

  public UpdateSpecialHourResponse errorReasons(List<ErrorReasonsEnum> errorReasons) {
    this.errorReasons = errorReasons;
    return this;
  }

  public UpdateSpecialHourResponse addErrorReasonsItem(ErrorReasonsEnum errorReasonsItem) {
    if (this.errorReasons == null) {
      this.errorReasons = new ArrayList<>();
    }
    this.errorReasons.add(errorReasonsItem);
    return this;
  }

  /**
   * Error message when updating store delivery hour. &#x60;null&#x60; indicates no error.
   * @return errorReasons
   */
  @javax.annotation.Nullable
  public List<ErrorReasonsEnum> getErrorReasons() {
    return errorReasons;
  }

  public void setErrorReasons(List<ErrorReasonsEnum> errorReasons) {
    this.errorReasons = errorReasons;
  }


  public UpdateSpecialHourResponse orderCount(Long orderCount) {
    this.orderCount = orderCount;
    return this;
  }

  /**
   * Total active order for the day.
   * @return orderCount
   */
  @javax.annotation.Nonnull
  public Long getOrderCount() {
    return orderCount;
  }

  public void setOrderCount(Long orderCount) {
    this.orderCount = orderCount;
  }


  public UpdateSpecialHourResponse scheduledOrderCount(Long scheduledOrderCount) {
    this.scheduledOrderCount = scheduledOrderCount;
    return this;
  }

  /**
   * Total scheduled order during store close period.
   * @return scheduledOrderCount
   */
  @javax.annotation.Nonnull
  public Long getScheduledOrderCount() {
    return scheduledOrderCount;
  }

  public void setScheduledOrderCount(Long scheduledOrderCount) {
    this.scheduledOrderCount = scheduledOrderCount;
  }


  public UpdateSpecialHourResponse closeImmediately(Boolean closeImmediately) {
    this.closeImmediately = closeImmediately;
    return this;
  }

  /**
   * Indicate the store status after updating special hours.
   * @return closeImmediately
   */
  @javax.annotation.Nonnull
  public Boolean getCloseImmediately() {
    return closeImmediately;
  }

  public void setCloseImmediately(Boolean closeImmediately) {
    this.closeImmediately = closeImmediately;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the UpdateSpecialHourResponse instance itself
   */
  public UpdateSpecialHourResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateSpecialHourResponse updateSpecialHourResponse = (UpdateSpecialHourResponse) o;
    return Objects.equals(this.errorReasons, updateSpecialHourResponse.errorReasons) &&
        Objects.equals(this.orderCount, updateSpecialHourResponse.orderCount) &&
        Objects.equals(this.scheduledOrderCount, updateSpecialHourResponse.scheduledOrderCount) &&
        Objects.equals(this.closeImmediately, updateSpecialHourResponse.closeImmediately)&&
        Objects.equals(this.additionalProperties, updateSpecialHourResponse.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorReasons, orderCount, scheduledOrderCount, closeImmediately, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateSpecialHourResponse {\n");
    sb.append("    errorReasons: ").append(toIndentedString(errorReasons)).append("\n");
    sb.append("    orderCount: ").append(toIndentedString(orderCount)).append("\n");
    sb.append("    scheduledOrderCount: ").append(toIndentedString(scheduledOrderCount)).append("\n");
    sb.append("    closeImmediately: ").append(toIndentedString(closeImmediately)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("errorReasons");
    openapiFields.add("orderCount");
    openapiFields.add("scheduledOrderCount");
    openapiFields.add("closeImmediately");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("orderCount");
    openapiRequiredFields.add("scheduledOrderCount");
    openapiRequiredFields.add("closeImmediately");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateSpecialHourResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateSpecialHourResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateSpecialHourResponse is not found in the empty JSON string", UpdateSpecialHourResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UpdateSpecialHourResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("errorReasons") != null && !jsonObj.get("errorReasons").isJsonNull() && !jsonObj.get("errorReasons").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `errorReasons` to be an array in the JSON string but got `%s`", jsonObj.get("errorReasons").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateSpecialHourResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateSpecialHourResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateSpecialHourResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateSpecialHourResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateSpecialHourResponse>() {
           @Override
           public void write(JsonWriter out, UpdateSpecialHourResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateSpecialHourResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             UpdateSpecialHourResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateSpecialHourResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateSpecialHourResponse
   * @throws IOException if the JSON string is invalid with respect to UpdateSpecialHourResponse
   */
  public static UpdateSpecialHourResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateSpecialHourResponse.class);
  }

  /**
   * Convert an instance of UpdateSpecialHourResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

